server:
  address:     ":8300"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true


database:
  autoMigrate: true
  default:
    type: "sqlite"
    link: "./data/db.sqlite"
    logLevel: "all"

