server:
  address:     ":8100"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  autoMigrate: true
  default:
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "master"
      debug: true
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "slave"
      debug: true
  test:
    type: "sqlite"
    link: "./data/db.sqlite"
    logLevel: "all"


