server:
  address:     ":8300"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true


database:
  autoMigrate: true
  default:
    type: "sqlite"
    link: "./data/db.sqlite"
    logLevel: "all"

cool-base:
  jwt:
    sso: false
    secret: "cool-base88776655"
    token:
      expire: 7200 # 2*3600
      refresh: 1296000 # 24*3600*15